<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso3' => 'AFG', 'iso2' => 'AF', 'phone_code' => '93', 'currency' => 'AFN', 'currency_name' => 'Afghan afghani', 'currency_symbol' => '؋'],
            ['name' => 'Aland Islands', 'iso3' => 'ALA', 'iso2' => 'AX', 'phone_code' => '358', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Albania', 'iso3' => 'ALB', 'iso2' => 'AL', 'phone_code' => '355', 'currency' => 'ALL', 'currency_name' => 'Albanian lek', 'currency_symbol' => 'Lek'],
            ['name' => 'Algeria', 'iso3' => 'DZA', 'iso2' => 'DZ', 'phone_code' => '213', 'currency' => 'DZD', 'currency_name' => 'Algerian dinar', 'currency_symbol' => 'دج'],
            ['name' => 'American Samoa', 'iso3' => 'ASM', 'iso2' => 'AS', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Andorra', 'iso3' => 'AND', 'iso2' => 'AD', 'phone_code' => '376', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Angola', 'iso3' => 'AGO', 'iso2' => 'AO', 'phone_code' => '244', 'currency' => 'AOA', 'currency_name' => 'Angolan kwanza', 'currency_symbol' => 'Kz'],
            ['name' => 'Anguilla', 'iso3' => 'AIA', 'iso2' => 'AI', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Antarctica', 'iso3' => 'ATA', 'iso2' => 'AQ', 'phone_code' => '672', 'currency' => 'AAD', 'currency_name' => 'Antarctican dollar', 'currency_symbol' => '$'],
            ['name' => 'Antigua and Barbuda', 'iso3' => 'ATG', 'iso2' => 'AG', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Argentina', 'iso3' => 'ARG', 'iso2' => 'AR', 'phone_code' => '54', 'currency' => 'ARS', 'currency_name' => 'Argentine peso', 'currency_symbol' => '$'],
            ['name' => 'Armenia', 'iso3' => 'ARM', 'iso2' => 'AM', 'phone_code' => '374', 'currency' => 'AMD', 'currency_name' => 'Armenian dram', 'currency_symbol' => '֏'],
            ['name' => 'Aruba', 'iso3' => 'ABW', 'iso2' => 'AW', 'phone_code' => '297', 'currency' => 'AWG', 'currency_name' => 'Aruban florin', 'currency_symbol' => 'ƒ'],
            ['name' => 'Australia', 'iso3' => 'AUS', 'iso2' => 'AU', 'phone_code' => '61', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'Austria', 'iso3' => 'AUT', 'iso2' => 'AT', 'phone_code' => '43', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Azerbaijan', 'iso3' => 'AZE', 'iso2' => 'AZ', 'phone_code' => '994', 'currency' => 'AZN', 'currency_name' => 'Azerbaijani manat', 'currency_symbol' => 'm'],
            ['name' => 'Bahrain', 'iso3' => 'BHR', 'iso2' => 'BH', 'phone_code' => '973', 'currency' => 'BHD', 'currency_name' => 'Bahraini dinar', 'currency_symbol' => '.د.ب'],
            ['name' => 'Bangladesh', 'iso3' => 'BGD', 'iso2' => 'BD', 'phone_code' => '880', 'currency' => 'BDT', 'currency_name' => 'Bangladeshi taka', 'currency_symbol' => '৳'],
            ['name' => 'Barbados', 'iso3' => 'BRB', 'iso2' => 'BB', 'phone_code' => '1', 'currency' => 'BBD', 'currency_name' => 'Barbadian dollar', 'currency_symbol' => 'Bds$'],
            ['name' => 'Belarus', 'iso3' => 'BLR', 'iso2' => 'BY', 'phone_code' => '375', 'currency' => 'BYN', 'currency_name' => 'Belarusian ruble', 'currency_symbol' => 'Br'],
            ['name' => 'Belgium', 'iso3' => 'BEL', 'iso2' => 'BE', 'phone_code' => '32', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Belize', 'iso3' => 'BLZ', 'iso2' => 'BZ', 'phone_code' => '501', 'currency' => 'BZD', 'currency_name' => 'Belize dollar', 'currency_symbol' => '$'],
            ['name' => 'Benin', 'iso3' => 'BEN', 'iso2' => 'BJ', 'phone_code' => '229', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Bermuda', 'iso3' => 'BMU', 'iso2' => 'BM', 'phone_code' => '1', 'currency' => 'BMD', 'currency_name' => 'Bermudian dollar', 'currency_symbol' => '$'],
            ['name' => 'Bhutan', 'iso3' => 'BTN', 'iso2' => 'BT', 'phone_code' => '975', 'currency' => 'BTN', 'currency_name' => 'Bhutanese ngultrum', 'currency_symbol' => 'Nu.'],
            ['name' => 'Bolivia', 'iso3' => 'BOL', 'iso2' => 'BO', 'phone_code' => '591', 'currency' => 'BOB', 'currency_name' => 'Bolivian boliviano', 'currency_symbol' => 'Bs.'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'iso3' => 'BES', 'iso2' => 'BQ', 'phone_code' => '599', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Bosnia and Herzegovina', 'iso3' => 'BIH', 'iso2' => 'BA', 'phone_code' => '387', 'currency' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina convertible mark', 'currency_symbol' => 'KM'],
            ['name' => 'Botswana', 'iso3' => 'BWA', 'iso2' => 'BW', 'phone_code' => '267', 'currency' => 'BWP', 'currency_name' => 'Botswana pula', 'currency_symbol' => 'P'],
            ['name' => 'Bouvet Island', 'iso3' => 'BVT', 'iso2' => 'BV', 'phone_code' => '0055', 'currency' => 'NOK', 'currency_name' => 'Norwegian krone', 'currency_symbol' => 'ko'],
            ['name' => 'Brazil', 'iso3' => 'BRA', 'iso2' => 'BR', 'phone_code' => '55', 'currency' => 'BRL', 'currency_name' => 'Brazilian real', 'currency_symbol' => 'R$'],
            ['name' => 'British Indian Ocean Territory', 'iso3' => 'IOT', 'iso2' => 'IO', 'phone_code' => '246', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Brunei', 'iso3' => 'BRN', 'iso2' => 'BN', 'phone_code' => '673', 'currency' => 'BND', 'currency_name' => 'Brunei dollar', 'currency_symbol' => 'B$'],
            ['name' => 'Bulgaria', 'iso3' => 'BGR', 'iso2' => 'BG', 'phone_code' => '359', 'currency' => 'BGN', 'currency_name' => 'Bulgarian lev', 'currency_symbol' => 'Лв.'],
            ['name' => 'Burkina Faso', 'iso3' => 'BFA', 'iso2' => 'BF', 'phone_code' => '226', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Burundi', 'iso3' => 'BDI', 'iso2' => 'BI', 'phone_code' => '257', 'currency' => 'BIF', 'currency_name' => 'Burundian franc', 'currency_symbol' => 'FBu'],
            ['name' => 'Cambodia', 'iso3' => 'KHM', 'iso2' => 'KH', 'phone_code' => '855', 'currency' => 'KHR', 'currency_name' => 'Cambodian riel', 'currency_symbol' => 'KHR'],
            ['name' => 'Cameroon', 'iso3' => 'CMR', 'iso2' => 'CM', 'phone_code' => '237', 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA'],
            ['name' => 'Canada', 'iso3' => 'CAN', 'iso2' => 'CA', 'phone_code' => '1', 'currency' => 'CAD', 'currency_name' => 'Canadian dollar', 'currency_symbol' => '$'],
            ['name' => 'Cape Verde', 'iso3' => 'CPV', 'iso2' => 'CV', 'phone_code' => '238', 'currency' => 'CVE', 'currency_name' => 'Cape Verdean escudo', 'currency_symbol' => '$'],
            ['name' => 'Cayman Islands', 'iso3' => 'CYM', 'iso2' => 'KY', 'phone_code' => '1', 'currency' => 'KYD', 'currency_name' => 'Cayman Islands dollar', 'currency_symbol' => '$'],
            ['name' => 'Central African Republic', 'iso3' => 'CAF', 'iso2' => 'CF', 'phone_code' => '236', 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA'],
            ['name' => 'Chad', 'iso3' => 'TCD', 'iso2' => 'TD', 'phone_code' => '235', 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA'],
            ['name' => 'Chile', 'iso3' => 'CHL', 'iso2' => 'CL', 'phone_code' => '56', 'currency' => 'CLP', 'currency_name' => 'Chilean peso', 'currency_symbol' => '$'],
            ['name' => 'China', 'iso3' => 'CHN', 'iso2' => 'CN', 'phone_code' => '86', 'currency' => 'CNY', 'currency_name' => 'Chinese yuan', 'currency_symbol' => '¥'],
            ['name' => 'Christmas Island', 'iso3' => 'CXR', 'iso2' => 'CX', 'phone_code' => '61', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'Cocos (Keeling) Islands', 'iso3' => 'CCK', 'iso2' => 'CC', 'phone_code' => '61', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'Colombia', 'iso3' => 'COL', 'iso2' => 'CO', 'phone_code' => '57', 'currency' => 'COP', 'currency_name' => 'Colombian peso', 'currency_symbol' => '$'],
            ['name' => 'Comoros', 'iso3' => 'COM', 'iso2' => 'KM', 'phone_code' => '269', 'currency' => 'KMF', 'currency_name' => 'Comorian franc', 'currency_symbol' => 'CF'],
            ['name' => 'Congo', 'iso3' => 'COG', 'iso2' => 'CG', 'phone_code' => '242', 'currency' => 'XAF', 'currency_name' => 'Congolese Franc', 'currency_symbol' => 'CDF'],
            ['name' => 'Cook Islands', 'iso3' => 'COK', 'iso2' => 'CK', 'phone_code' => '682', 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$'],
            ['name' => 'Costa Rica', 'iso3' => 'CRI', 'iso2' => 'CR', 'phone_code' => '506', 'currency' => 'CRC', 'currency_name' => 'Costa Rican colón', 'currency_symbol' => '₡'],
            ['name' => 'Cote D\'Ivoire (Ivory Coast)', 'iso3' => 'CIV', 'iso2' => 'CI', 'phone_code' => '225', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Croatia', 'iso3' => 'HRV', 'iso2' => 'HR', 'phone_code' => '385', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Cuba', 'iso3' => 'CUB', 'iso2' => 'CU', 'phone_code' => '53', 'currency' => 'CUP', 'currency_name' => 'Cuban peso', 'currency_symbol' => '$'],
            ['name' => 'Curaçao', 'iso3' => 'CUW', 'iso2' => 'CW', 'phone_code' => '599', 'currency' => 'ANG', 'currency_name' => 'Netherlands Antillean guilder', 'currency_symbol' => 'ƒ'],
            ['name' => 'Cyprus', 'iso3' => 'CYP', 'iso2' => 'CY', 'phone_code' => '357', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Czech Republic', 'iso3' => 'CZE', 'iso2' => 'CZ', 'phone_code' => '420', 'currency' => 'CZK', 'currency_name' => 'Czech koruna', 'currency_symbol' => 'Kč'],
            ['name' => 'Democratic Republic of the Congo', 'iso3' => 'COD', 'iso2' => 'CD', 'phone_code' => '243', 'currency' => 'CDF', 'currency_name' => 'Congolese Franc', 'currency_symbol' => 'FC'],
            ['name' => 'Denmark', 'iso3' => 'DNK', 'iso2' => 'DK', 'phone_code' => '45', 'currency' => 'DKK', 'currency_name' => 'Danish krone', 'currency_symbol' => 'Kr.'],
            ['name' => 'Djibouti', 'iso3' => 'DJI', 'iso2' => 'DJ', 'phone_code' => '253', 'currency' => 'DJF', 'currency_name' => 'Djiboutian franc', 'currency_symbol' => 'Fdj'],
            ['name' => 'Dominica', 'iso3' => 'DMA', 'iso2' => 'DM', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Dominican Republic', 'iso3' => 'DOM', 'iso2' => 'DO', 'phone_code' => '1', 'currency' => 'DOP', 'currency_name' => 'Dominican peso', 'currency_symbol' => '$'],
            ['name' => 'Ecuador', 'iso3' => 'ECU', 'iso2' => 'EC', 'phone_code' => '593', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Egypt', 'iso3' => 'EGY', 'iso2' => 'EG', 'phone_code' => '20', 'currency' => 'EGP', 'currency_name' => 'Egyptian pound', 'currency_symbol' => 'ج.م'],
            ['name' => 'El Salvador', 'iso3' => 'SLV', 'iso2' => 'SV', 'phone_code' => '503', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Equatorial Guinea', 'iso3' => 'GNQ', 'iso2' => 'GQ', 'phone_code' => '240', 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA'],
            ['name' => 'Eritrea', 'iso3' => 'ERI', 'iso2' => 'ER', 'phone_code' => '291', 'currency' => 'ERN', 'currency_name' => 'Eritrean nakfa', 'currency_symbol' => 'Nfk'],
            ['name' => 'Estonia', 'iso3' => 'EST', 'iso2' => 'EE', 'phone_code' => '372', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Eswatini', 'iso3' => 'SWZ', 'iso2' => 'SZ', 'phone_code' => '268', 'currency' => 'SZL', 'currency_name' => 'Lilangeni', 'currency_symbol' => 'E'],
            ['name' => 'Ethiopia', 'iso3' => 'ETH', 'iso2' => 'ET', 'phone_code' => '251', 'currency' => 'ETB', 'currency_name' => 'Ethiopian birr', 'currency_symbol' => 'Nkf'],
            ['name' => 'Falkland Islands', 'iso3' => 'FLK', 'iso2' => 'FK', 'phone_code' => '500', 'currency' => 'FKP', 'currency_name' => 'Falkland Islands pound', 'currency_symbol' => '£'],
            ['name' => 'Faroe Islands', 'iso3' => 'FRO', 'iso2' => 'FO', 'phone_code' => '298', 'currency' => 'DKK', 'currency_name' => 'Danish krone', 'currency_symbol' => 'Kr.'],
            ['name' => 'Fiji Islands', 'iso3' => 'FJI', 'iso2' => 'FJ', 'phone_code' => '679', 'currency' => 'FJD', 'currency_name' => 'Fijian dollar', 'currency_symbol' => 'FJ$'],
            ['name' => 'Finland', 'iso3' => 'FIN', 'iso2' => 'FI', 'phone_code' => '358', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'France', 'iso3' => 'FRA', 'iso2' => 'FR', 'phone_code' => '33', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'French Guiana', 'iso3' => 'GUF', 'iso2' => 'GF', 'phone_code' => '594', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'French Polynesia', 'iso3' => 'PYF', 'iso2' => 'PF', 'phone_code' => '689', 'currency' => 'XPF', 'currency_name' => 'CFP franc', 'currency_symbol' => '₣'],
            ['name' => 'French Southern Territories', 'iso3' => 'ATF', 'iso2' => 'TF', 'phone_code' => '262', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Gabon', 'iso3' => 'GAB', 'iso2' => 'GA', 'phone_code' => '241', 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA'],
            ['name' => 'Georgia', 'iso3' => 'GEO', 'iso2' => 'GE', 'phone_code' => '995', 'currency' => 'GEL', 'currency_name' => 'Georgian lari', 'currency_symbol' => 'ლ'],
            ['name' => 'Germany', 'iso3' => 'DEU', 'iso2' => 'DE', 'phone_code' => '49', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Ghana', 'iso3' => 'GHA', 'iso2' => 'GH', 'phone_code' => '233', 'currency' => 'GHS', 'currency_name' => 'Ghanaian cedi', 'currency_symbol' => 'GH₵'],
            ['name' => 'Gibraltar', 'iso3' => 'GIB', 'iso2' => 'GI', 'phone_code' => '350', 'currency' => 'GIP', 'currency_name' => 'Gibraltar pound', 'currency_symbol' => '£'],
            ['name' => 'Greece', 'iso3' => 'GRC', 'iso2' => 'GR', 'phone_code' => '30', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Greenland', 'iso3' => 'GRL', 'iso2' => 'GL', 'phone_code' => '299', 'currency' => 'DKK', 'currency_name' => 'Danish krone', 'currency_symbol' => 'Kr.'],
            ['name' => 'Grenada', 'iso3' => 'GRD', 'iso2' => 'GD', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Guadeloupe', 'iso3' => 'GLP', 'iso2' => 'GP', 'phone_code' => '590', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Guam', 'iso3' => 'GUM', 'iso2' => 'GU', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Guatemala', 'iso3' => 'GTM', 'iso2' => 'GT', 'phone_code' => '502', 'currency' => 'GTQ', 'currency_name' => 'Guatemalan quetzal', 'currency_symbol' => 'Q'],
            ['name' => 'Guernsey', 'iso3' => 'GGY', 'iso2' => 'GG', 'phone_code' => '44', 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£'],
            ['name' => 'Guinea', 'iso3' => 'GIN', 'iso2' => 'GN', 'phone_code' => '224', 'currency' => 'GNF', 'currency_name' => 'Guinean franc', 'currency_symbol' => 'FG'],
            ['name' => 'Guinea-Bissau', 'iso3' => 'GNB', 'iso2' => 'GW', 'phone_code' => '245', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Guyana', 'iso3' => 'GUY', 'iso2' => 'GY', 'phone_code' => '592', 'currency' => 'GYD', 'currency_name' => 'Guyanese dollar', 'currency_symbol' => '$'],
            ['name' => 'Haiti', 'iso3' => 'HTI', 'iso2' => 'HT', 'phone_code' => '509', 'currency' => 'HTG', 'currency_name' => 'Haitian gourde', 'currency_symbol' => 'G'],
            ['name' => 'Heard Island and McDonald Islands', 'iso3' => 'HMD', 'iso2' => 'HM', 'phone_code' => '672', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'Honduras', 'iso3' => 'HND', 'iso2' => 'HN', 'phone_code' => '504', 'currency' => 'HNL', 'currency_name' => 'Honduran lempira', 'currency_symbol' => 'L'],
            ['name' => 'Hong Kong S.A.R.', 'iso3' => 'HKG', 'iso2' => 'HK', 'phone_code' => '852', 'currency' => 'HKD', 'currency_name' => 'Hong Kong dollar', 'currency_symbol' => '$'],
            ['name' => 'Hungary', 'iso3' => 'HUN', 'iso2' => 'HU', 'phone_code' => '36', 'currency' => 'HUF', 'currency_name' => 'Hungarian forint', 'currency_symbol' => 'Ft'],
            ['name' => 'Iceland', 'iso3' => 'ISL', 'iso2' => 'IS', 'phone_code' => '354', 'currency' => 'ISK', 'currency_name' => 'Icelandic króna', 'currency_symbol' => 'ko'],
            ['name' => 'India', 'iso3' => 'IND', 'iso2' => 'IN', 'phone_code' => '91', 'currency' => 'INR', 'currency_name' => 'Indian rupee', 'currency_symbol' => '₹'],
            ['name' => 'Indonesia', 'iso3' => 'IDN', 'iso2' => 'ID', 'phone_code' => '62', 'currency' => 'IDR', 'currency_name' => 'Indonesian rupiah', 'currency_symbol' => 'Rp'],
            ['name' => 'Iran', 'iso3' => 'IRN', 'iso2' => 'IR', 'phone_code' => '98', 'currency' => 'IRR', 'currency_name' => 'Iranian rial', 'currency_symbol' => '﷼'],
            ['name' => 'Iraq', 'iso3' => 'IRQ', 'iso2' => 'IQ', 'phone_code' => '964', 'currency' => 'IQD', 'currency_name' => 'Iraqi dinar', 'currency_symbol' => 'د.ع'],
            ['name' => 'Ireland', 'iso3' => 'IRL', 'iso2' => 'IE', 'phone_code' => '353', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Isle of Man', 'iso3' => 'IMN', 'iso2' => 'IM', 'phone_code' => '44', 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£'],
            ['name' => 'Israel', 'iso3' => 'ISR', 'iso2' => 'IL', 'phone_code' => '972', 'currency' => 'ILS', 'currency_name' => 'Israeli new shekel', 'currency_symbol' => '₪'],
            ['name' => 'Italy', 'iso3' => 'ITA', 'iso2' => 'IT', 'phone_code' => '39', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Jamaica', 'iso3' => 'JAM', 'iso2' => 'JM', 'phone_code' => '1', 'currency' => 'JMD', 'currency_name' => 'Jamaican dollar', 'currency_symbol' => 'J$'],
            ['name' => 'Japan', 'iso3' => 'JPN', 'iso2' => 'JP', 'phone_code' => '81', 'currency' => 'JPY', 'currency_name' => 'Japanese yen', 'currency_symbol' => '¥'],
            ['name' => 'Jersey', 'iso3' => 'JEY', 'iso2' => 'JE', 'phone_code' => '44', 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£'],
            ['name' => 'Jordan', 'iso3' => 'JOR', 'iso2' => 'JO', 'phone_code' => '962', 'currency' => 'JOD', 'currency_name' => 'Jordanian dinar', 'currency_symbol' => 'ا.د'],
            ['name' => 'Kazakhstan', 'iso3' => 'KAZ', 'iso2' => 'KZ', 'phone_code' => '7', 'currency' => 'KZT', 'currency_name' => 'Kazakhstani tenge', 'currency_symbol' => 'лв'],
            ['name' => 'Kenya', 'iso3' => 'KEN', 'iso2' => 'KE', 'phone_code' => '254', 'currency' => 'KES', 'currency_name' => 'Kenyan shilling', 'currency_symbol' => 'KSh'],
            ['name' => 'Kiribati', 'iso3' => 'KIR', 'iso2' => 'KI', 'phone_code' => '686', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'Kosovo', 'iso3' => 'XKX', 'iso2' => 'XK', 'phone_code' => '383', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Kuwait', 'iso3' => 'KWT', 'iso2' => 'KW', 'phone_code' => '965', 'currency' => 'KWD', 'currency_name' => 'Kuwaiti dinar', 'currency_symbol' => 'ك.د'],
            ['name' => 'Kyrgyzstan', 'iso3' => 'KGZ', 'iso2' => 'KG', 'phone_code' => '996', 'currency' => 'KGS', 'currency_name' => 'Kyrgyzstani som', 'currency_symbol' => 'лв'],
            ['name' => 'Laos', 'iso3' => 'LAO', 'iso2' => 'LA', 'phone_code' => '856', 'currency' => 'LAK', 'currency_name' => 'Lao kip', 'currency_symbol' => '₭'],
            ['name' => 'Latvia', 'iso3' => 'LVA', 'iso2' => 'LV', 'phone_code' => '371', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Lebanon', 'iso3' => 'LBN', 'iso2' => 'LB', 'phone_code' => '961', 'currency' => 'LBP', 'currency_name' => 'Lebanese pound', 'currency_symbol' => '£'],
            ['name' => 'Lesotho', 'iso3' => 'LSO', 'iso2' => 'LS', 'phone_code' => '266', 'currency' => 'LSL', 'currency_name' => 'Lesotho loti', 'currency_symbol' => 'L'],
            ['name' => 'Liberia', 'iso3' => 'LBR', 'iso2' => 'LR', 'phone_code' => '231', 'currency' => 'LRD', 'currency_name' => 'Liberian dollar', 'currency_symbol' => '$'],
            ['name' => 'Libya', 'iso3' => 'LBY', 'iso2' => 'LY', 'phone_code' => '218', 'currency' => 'LYD', 'currency_name' => 'Libyan dinar', 'currency_symbol' => 'د.ل'],
            ['name' => 'Liechtenstein', 'iso3' => 'LIE', 'iso2' => 'LI', 'phone_code' => '423', 'currency' => 'CHF', 'currency_name' => 'Swiss franc', 'currency_symbol' => 'CHf'],
            ['name' => 'Lithuania', 'iso3' => 'LTU', 'iso2' => 'LT', 'phone_code' => '370', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Luxembourg', 'iso3' => 'LUX', 'iso2' => 'LU', 'phone_code' => '352', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Macau S.A.R.', 'iso3' => 'MAC', 'iso2' => 'MO', 'phone_code' => '853', 'currency' => 'MOP', 'currency_name' => 'Macanese pataca', 'currency_symbol' => '$'],
            ['name' => 'Madagascar', 'iso3' => 'MDG', 'iso2' => 'MG', 'phone_code' => '261', 'currency' => 'MGA', 'currency_name' => 'Malagasy ariary', 'currency_symbol' => 'Ar'],
            ['name' => 'Malawi', 'iso3' => 'MWI', 'iso2' => 'MW', 'phone_code' => '265', 'currency' => 'MWK', 'currency_name' => 'Malawian kwacha', 'currency_symbol' => 'MK'],
            ['name' => 'Malaysia', 'iso3' => 'MYS', 'iso2' => 'MY', 'phone_code' => '60', 'currency' => 'MYR', 'currency_name' => 'Malaysian ringgit', 'currency_symbol' => 'RM'],
            ['name' => 'Maldives', 'iso3' => 'MDV', 'iso2' => 'MV', 'phone_code' => '960', 'currency' => 'MVR', 'currency_name' => 'Maldivian rufiyaa', 'currency_symbol' => 'Rf'],
            ['name' => 'Mali', 'iso3' => 'MLI', 'iso2' => 'ML', 'phone_code' => '223', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Malta', 'iso3' => 'MLT', 'iso2' => 'MT', 'phone_code' => '356', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Marshall Islands', 'iso3' => 'MHL', 'iso2' => 'MH', 'phone_code' => '692', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Martinique', 'iso3' => 'MTQ', 'iso2' => 'MQ', 'phone_code' => '596', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Mauritania', 'iso3' => 'MRT', 'iso2' => 'MR', 'phone_code' => '222', 'currency' => 'MRU', 'currency_name' => 'Mauritanian ouguiya', 'currency_symbol' => 'UM'],
            ['name' => 'Mauritius', 'iso3' => 'MUS', 'iso2' => 'MU', 'phone_code' => '230', 'currency' => 'MUR', 'currency_name' => 'Mauritian rupee', 'currency_symbol' => '₨'],
            ['name' => 'Mayotte', 'iso3' => 'MYT', 'iso2' => 'YT', 'phone_code' => '262', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Mexico', 'iso3' => 'MEX', 'iso2' => 'MX', 'phone_code' => '52', 'currency' => 'MXN', 'currency_name' => 'Mexican peso', 'currency_symbol' => '$'],
            ['name' => 'Micronesia', 'iso3' => 'FSM', 'iso2' => 'FM', 'phone_code' => '691', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Moldova', 'iso3' => 'MDA', 'iso2' => 'MD', 'phone_code' => '373', 'currency' => 'MDL', 'currency_name' => 'Moldovan leu', 'currency_symbol' => 'L'],
            ['name' => 'Monaco', 'iso3' => 'MCO', 'iso2' => 'MC', 'phone_code' => '377', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Mongolia', 'iso3' => 'MNG', 'iso2' => 'MN', 'phone_code' => '976', 'currency' => 'MNT', 'currency_name' => 'Mongolian tögrög', 'currency_symbol' => '₮'],
            ['name' => 'Montenegro', 'iso3' => 'MNE', 'iso2' => 'ME', 'phone_code' => '382', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Montserrat', 'iso3' => 'MSR', 'iso2' => 'MS', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Morocco', 'iso3' => 'MAR', 'iso2' => 'MA', 'phone_code' => '212', 'currency' => 'MAD', 'currency_name' => 'Moroccan dirham', 'currency_symbol' => 'DH'],
            ['name' => 'Mozambique', 'iso3' => 'MOZ', 'iso2' => 'MZ', 'phone_code' => '258', 'currency' => 'MZN', 'currency_name' => 'Mozambican metical', 'currency_symbol' => 'MT'],
            ['name' => 'Myanmar', 'iso3' => 'MMR', 'iso2' => 'MM', 'phone_code' => '95', 'currency' => 'MMK', 'currency_name' => 'Burmese kyat', 'currency_symbol' => 'K'],
            ['name' => 'Namibia', 'iso3' => 'NAM', 'iso2' => 'NA', 'phone_code' => '264', 'currency' => 'NAD', 'currency_name' => 'Namibian dollar', 'currency_symbol' => '$'],
            ['name' => 'Nauru', 'iso3' => 'NRU', 'iso2' => 'NR', 'phone_code' => '674', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'Nepal', 'iso3' => 'NPL', 'iso2' => 'NP', 'phone_code' => '977', 'currency' => 'NPR', 'currency_name' => 'Nepalese rupee', 'currency_symbol' => '₨'],
            ['name' => 'Netherlands', 'iso3' => 'NLD', 'iso2' => 'NL', 'phone_code' => '31', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'New Caledonia', 'iso3' => 'NCL', 'iso2' => 'NC', 'phone_code' => '687', 'currency' => 'XPF', 'currency_name' => 'CFP franc', 'currency_symbol' => '₣'],
            ['name' => 'New Zealand', 'iso3' => 'NZL', 'iso2' => 'NZ', 'phone_code' => '64', 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$'],
            ['name' => 'Nicaragua', 'iso3' => 'NIC', 'iso2' => 'NI', 'phone_code' => '505', 'currency' => 'NIO', 'currency_name' => 'Nicaraguan córdoba', 'currency_symbol' => 'C$'],
            ['name' => 'Niger', 'iso3' => 'NER', 'iso2' => 'NE', 'phone_code' => '227', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Nigeria', 'iso3' => 'NGA', 'iso2' => 'NG', 'phone_code' => '234', 'currency' => 'NGN', 'currency_name' => 'Nigerian naira', 'currency_symbol' => '₦'],
            ['name' => 'Niue', 'iso3' => 'NIU', 'iso2' => 'NU', 'phone_code' => '683', 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$'],
            ['name' => 'Norfolk Island', 'iso3' => 'NFK', 'iso2' => 'NF', 'phone_code' => '672', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'North Korea', 'iso3' => 'PRK', 'iso2' => 'KP', 'phone_code' => '850', 'currency' => 'KPW', 'currency_name' => 'North Korean Won', 'currency_symbol' => '₩'],
            ['name' => 'North Macedonia', 'iso3' => 'MKD', 'iso2' => 'MK', 'phone_code' => '389', 'currency' => 'MKD', 'currency_name' => 'Denar', 'currency_symbol' => 'ден'],
            ['name' => 'Northern Mariana Islands', 'iso3' => 'MNP', 'iso2' => 'MP', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Norway', 'iso3' => 'NOR', 'iso2' => 'NO', 'phone_code' => '47', 'currency' => 'NOK', 'currency_name' => 'Norwegian krone', 'currency_symbol' => 'ko'],
            ['name' => 'Oman', 'iso3' => 'OMN', 'iso2' => 'OM', 'phone_code' => '968', 'currency' => 'OMR', 'currency_name' => 'Omani rial', 'currency_symbol' => '.ع.ر'],
            ['name' => 'Pakistan', 'iso3' => 'PAK', 'iso2' => 'PK', 'phone_code' => '92', 'currency' => 'PKR', 'currency_name' => 'Pakistani rupee', 'currency_symbol' => '₨'],
            ['name' => 'Palau', 'iso3' => 'PLW', 'iso2' => 'PW', 'phone_code' => '680', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Palestinian Territory Occupied', 'iso3' => 'PSE', 'iso2' => 'PS', 'phone_code' => '970', 'currency' => 'ILS', 'currency_name' => 'Israeli new shekel', 'currency_symbol' => '₪'],
            ['name' => 'Panama', 'iso3' => 'PAN', 'iso2' => 'PA', 'phone_code' => '507', 'currency' => 'PAB', 'currency_name' => 'Panamanian balboa', 'currency_symbol' => 'B/.'],
            ['name' => 'Papua New Guinea', 'iso3' => 'PNG', 'iso2' => 'PG', 'phone_code' => '675', 'currency' => 'PGK', 'currency_name' => 'Papua New Guinean kina', 'currency_symbol' => 'K'],
            ['name' => 'Paraguay', 'iso3' => 'PRY', 'iso2' => 'PY', 'phone_code' => '595', 'currency' => 'PYG', 'currency_name' => 'Paraguayan guarani', 'currency_symbol' => '₲'],
            ['name' => 'Peru', 'iso3' => 'PER', 'iso2' => 'PE', 'phone_code' => '51', 'currency' => 'PEN', 'currency_name' => 'Peruvian sol', 'currency_symbol' => 'S/.'],
            ['name' => 'Philippines', 'iso3' => 'PHL', 'iso2' => 'PH', 'phone_code' => '63', 'currency' => 'PHP', 'currency_name' => 'Philippine peso', 'currency_symbol' => '₱'],
            ['name' => 'Pitcairn Island', 'iso3' => 'PCN', 'iso2' => 'PN', 'phone_code' => '870', 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$'],
            ['name' => 'Poland', 'iso3' => 'POL', 'iso2' => 'PL', 'phone_code' => '48', 'currency' => 'PLN', 'currency_name' => 'Polish złoty', 'currency_symbol' => 'zł'],
            ['name' => 'Portugal', 'iso3' => 'PRT', 'iso2' => 'PT', 'phone_code' => '351', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Puerto Rico', 'iso3' => 'PRI', 'iso2' => 'PR', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Qatar', 'iso3' => 'QAT', 'iso2' => 'QA', 'phone_code' => '974', 'currency' => 'QAR', 'currency_name' => 'Qatari riyal', 'currency_symbol' => 'ق.ر'],
            ['name' => 'Reunion', 'iso3' => 'REU', 'iso2' => 'RE', 'phone_code' => '262', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Romania', 'iso3' => 'ROU', 'iso2' => 'RO', 'phone_code' => '40', 'currency' => 'RON', 'currency_name' => 'Romanian leu', 'currency_symbol' => 'lei'],
            ['name' => 'Russia', 'iso3' => 'RUS', 'iso2' => 'RU', 'phone_code' => '7', 'currency' => 'RUB', 'currency_name' => 'Russian ruble', 'currency_symbol' => '₽'],
            ['name' => 'Rwanda', 'iso3' => 'RWA', 'iso2' => 'RW', 'phone_code' => '250', 'currency' => 'RWF', 'currency_name' => 'Rwandan franc', 'currency_symbol' => 'FRw'],
            ['name' => 'Saint Helena', 'iso3' => 'SHN', 'iso2' => 'SH', 'phone_code' => '290', 'currency' => 'SHP', 'currency_name' => 'Saint Helena pound', 'currency_symbol' => '£'],
            ['name' => 'Saint Kitts and Nevis', 'iso3' => 'KNA', 'iso2' => 'KN', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Saint Lucia', 'iso3' => 'LCA', 'iso2' => 'LC', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Saint Pierre and Miquelon', 'iso3' => 'SPM', 'iso2' => 'PM', 'phone_code' => '508', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso3' => 'VCT', 'iso2' => 'VC', 'phone_code' => '1', 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$'],
            ['name' => 'Saint-Barthelemy', 'iso3' => 'BLM', 'iso2' => 'BL', 'phone_code' => '590', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Saint-Martin (French part)', 'iso3' => 'MAF', 'iso2' => 'MF', 'phone_code' => '590', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Samoa', 'iso3' => 'WSM', 'iso2' => 'WS', 'phone_code' => '685', 'currency' => 'WST', 'currency_name' => 'Samoan tālā', 'currency_symbol' => 'SAT'],
            ['name' => 'San Marino', 'iso3' => 'SMR', 'iso2' => 'SM', 'phone_code' => '378', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Sao Tome and Principe', 'iso3' => 'STP', 'iso2' => 'ST', 'phone_code' => '239', 'currency' => 'STN', 'currency_name' => 'Dobra', 'currency_symbol' => 'Db'],
            ['name' => 'Saudi Arabia', 'iso3' => 'SAU', 'iso2' => 'SA', 'phone_code' => '966', 'currency' => 'SAR', 'currency_name' => 'Saudi riyal', 'currency_symbol' => '﷼'],
            ['name' => 'Senegal', 'iso3' => 'SEN', 'iso2' => 'SN', 'phone_code' => '221', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Serbia', 'iso3' => 'SRB', 'iso2' => 'RS', 'phone_code' => '381', 'currency' => 'RSD', 'currency_name' => 'Serbian dinar', 'currency_symbol' => 'din'],
            ['name' => 'Seychelles', 'iso3' => 'SYC', 'iso2' => 'SC', 'phone_code' => '248', 'currency' => 'SCR', 'currency_name' => 'Seychellois rupee', 'currency_symbol' => 'SRe'],
            ['name' => 'Sierra Leone', 'iso3' => 'SLE', 'iso2' => 'SL', 'phone_code' => '232', 'currency' => 'SLL', 'currency_name' => 'Sierra Leonean leone', 'currency_symbol' => 'Le'],
            ['name' => 'Singapore', 'iso3' => 'SGP', 'iso2' => 'SG', 'phone_code' => '65', 'currency' => 'SGD', 'currency_name' => 'Singapore dollar', 'currency_symbol' => '$'],
            ['name' => 'Sint Maarten (Dutch part)', 'iso3' => 'SXM', 'iso2' => 'SX', 'phone_code' => '1721', 'currency' => 'ANG', 'currency_name' => 'Netherlands Antillean guilder', 'currency_symbol' => 'ƒ'],
            ['name' => 'Slovakia', 'iso3' => 'SVK', 'iso2' => 'SK', 'phone_code' => '421', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Slovenia', 'iso3' => 'SVN', 'iso2' => 'SI', 'phone_code' => '386', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Solomon Islands', 'iso3' => 'SLB', 'iso2' => 'SB', 'phone_code' => '677', 'currency' => 'SBD', 'currency_name' => 'Solomon Islands dollar', 'currency_symbol' => 'Si$'],
            ['name' => 'Somalia', 'iso3' => 'SOM', 'iso2' => 'SO', 'phone_code' => '252', 'currency' => 'SOS', 'currency_name' => 'Somali shilling', 'currency_symbol' => 'Sh.so.'],
            ['name' => 'South Africa', 'iso3' => 'ZAF', 'iso2' => 'ZA', 'phone_code' => '27', 'currency' => 'ZAR', 'currency_name' => 'South African rand', 'currency_symbol' => 'R'],
            ['name' => 'South Georgia', 'iso3' => 'SGS', 'iso2' => 'GS', 'phone_code' => '500', 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£'],
            ['name' => 'South Korea', 'iso3' => 'KOR', 'iso2' => 'KR', 'phone_code' => '82', 'currency' => 'KRW', 'currency_name' => 'Won', 'currency_symbol' => '₩'],
            ['name' => 'South Sudan', 'iso3' => 'SSD', 'iso2' => 'SS', 'phone_code' => '211', 'currency' => 'SSP', 'currency_name' => 'South Sudanese pound', 'currency_symbol' => '£'],
            ['name' => 'Spain', 'iso3' => 'ESP', 'iso2' => 'ES', 'phone_code' => '34', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Sri Lanka', 'iso3' => 'LKA', 'iso2' => 'LK', 'phone_code' => '94', 'currency' => 'LKR', 'currency_name' => 'Sri Lankan rupee', 'currency_symbol' => 'Rs'],
            ['name' => 'Sudan', 'iso3' => 'SDN', 'iso2' => 'SD', 'phone_code' => '249', 'currency' => 'SDG', 'currency_name' => 'Sudanese pound', 'currency_symbol' => '.س.ج'],
            ['name' => 'Suriname', 'iso3' => 'SUR', 'iso2' => 'SR', 'phone_code' => '597', 'currency' => 'SRD', 'currency_name' => 'Surinamese dollar', 'currency_symbol' => '$'],
            ['name' => 'Svalbard and Jan Mayen Islands', 'iso3' => 'SJM', 'iso2' => 'SJ', 'phone_code' => '47', 'currency' => 'NOK', 'currency_name' => 'Norwegian krone', 'currency_symbol' => 'ko'],
            ['name' => 'Sweden', 'iso3' => 'SWE', 'iso2' => 'SE', 'phone_code' => '46', 'currency' => 'SEK', 'currency_name' => 'Swedish krona', 'currency_symbol' => 'ko'],
            ['name' => 'Switzerland', 'iso3' => 'CHE', 'iso2' => 'CH', 'phone_code' => '41', 'currency' => 'CHF', 'currency_name' => 'Swiss franc', 'currency_symbol' => 'CHf'],
            ['name' => 'Syria', 'iso3' => 'SYR', 'iso2' => 'SY', 'phone_code' => '963', 'currency' => 'SYP', 'currency_name' => 'Syrian pound', 'currency_symbol' => 'LS'],
            ['name' => 'Taiwan', 'iso3' => 'TWN', 'iso2' => 'TW', 'phone_code' => '886', 'currency' => 'TWD', 'currency_name' => 'New Taiwan dollar', 'currency_symbol' => '$'],
            ['name' => 'Tajikistan', 'iso3' => 'TJK', 'iso2' => 'TJ', 'phone_code' => '992', 'currency' => 'TJS', 'currency_name' => 'Tajikistani somoni', 'currency_symbol' => 'SM'],
            ['name' => 'Tanzania', 'iso3' => 'TZA', 'iso2' => 'TZ', 'phone_code' => '255', 'currency' => 'TZS', 'currency_name' => 'Tanzanian shilling', 'currency_symbol' => 'TSh'],
            ['name' => 'Thailand', 'iso3' => 'THA', 'iso2' => 'TH', 'phone_code' => '66', 'currency' => 'THB', 'currency_name' => 'Thai baht', 'currency_symbol' => '฿'],
            ['name' => 'The Bahamas', 'iso3' => 'BHS', 'iso2' => 'BS', 'phone_code' => '1', 'currency' => 'BSD', 'currency_name' => 'Bahamian dollar', 'currency_symbol' => 'B$'],
            ['name' => 'The Gambia', 'iso3' => 'GMB', 'iso2' => 'GM', 'phone_code' => '220', 'currency' => 'GMD', 'currency_name' => 'Gambian dalasi', 'currency_symbol' => 'D'],
            ['name' => 'Timor-Leste', 'iso3' => 'TLS', 'iso2' => 'TL', 'phone_code' => '670', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Togo', 'iso3' => 'TGO', 'iso2' => 'TG', 'phone_code' => '228', 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['name' => 'Tokelau', 'iso3' => 'TKL', 'iso2' => 'TK', 'phone_code' => '690', 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$'],
            ['name' => 'Tonga', 'iso3' => 'TON', 'iso2' => 'TO', 'phone_code' => '676', 'currency' => 'TOP', 'currency_name' => 'Tongan paʻanga', 'currency_symbol' => '$'],
            ['name' => 'Trinidad and Tobago', 'iso3' => 'TTO', 'iso2' => 'TT', 'phone_code' => '1', 'currency' => 'TTD', 'currency_name' => 'Trinidad and Tobago dollar', 'currency_symbol' => '$'],
            ['name' => 'Tunisia', 'iso3' => 'TUN', 'iso2' => 'TN', 'phone_code' => '216', 'currency' => 'TND', 'currency_name' => 'Tunisian dinar', 'currency_symbol' => 'ت.د'],
            ['name' => 'Turkey', 'iso3' => 'TUR', 'iso2' => 'TR', 'phone_code' => '90', 'currency' => 'TRY', 'currency_name' => 'Turkish lira', 'currency_symbol' => '₺'],
            ['name' => 'Turkmenistan', 'iso3' => 'TKM', 'iso2' => 'TM', 'phone_code' => '993', 'currency' => 'TMT', 'currency_name' => 'Turkmenistan manat', 'currency_symbol' => 'T'],
            ['name' => 'Turks and Caicos Islands', 'iso3' => 'TCA', 'iso2' => 'TC', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Tuvalu', 'iso3' => 'TUV', 'iso2' => 'TV', 'phone_code' => '688', 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['name' => 'Uganda', 'iso3' => 'UGA', 'iso2' => 'UG', 'phone_code' => '256', 'currency' => 'UGX', 'currency_name' => 'Ugandan shilling', 'currency_symbol' => 'USh'],
            ['name' => 'Ukraine', 'iso3' => 'UKR', 'iso2' => 'UA', 'phone_code' => '380', 'currency' => 'UAH', 'currency_name' => 'Ukrainian hryvnia', 'currency_symbol' => '₴'],
            ['name' => 'United Arab Emirates', 'iso3' => 'ARE', 'iso2' => 'AE', 'phone_code' => '971', 'currency' => 'AED', 'currency_name' => 'United Arab Emirates dirham', 'currency_symbol' => 'إ.د'],
            ['name' => 'United Kingdom', 'iso3' => 'GBR', 'iso2' => 'GB', 'phone_code' => '44', 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£'],
            ['name' => 'United States', 'iso3' => 'USA', 'iso2' => 'US', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'United States Minor Outlying Islands', 'iso3' => 'UMI', 'iso2' => 'UM', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Uruguay', 'iso3' => 'URY', 'iso2' => 'UY', 'phone_code' => '598', 'currency' => 'UYU', 'currency_name' => 'Uruguayan peso', 'currency_symbol' => '$'],
            ['name' => 'Uzbekistan', 'iso3' => 'UZB', 'iso2' => 'UZ', 'phone_code' => '998', 'currency' => 'UZS', 'currency_name' => 'Uzbekistani soʻm', 'currency_symbol' => 'лв'],
            ['name' => 'Vanuatu', 'iso3' => 'VUT', 'iso2' => 'VU', 'phone_code' => '678', 'currency' => 'VUV', 'currency_name' => 'Vanuatu vatu', 'currency_symbol' => 'VT'],
            ['name' => 'Vatican City State (Holy See)', 'iso3' => 'VAT', 'iso2' => 'VA', 'phone_code' => '379', 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['name' => 'Venezuela', 'iso3' => 'VEN', 'iso2' => 'VE', 'phone_code' => '58', 'currency' => 'VES', 'currency_name' => 'Bolívar', 'currency_symbol' => 'Bs'],
            ['name' => 'Vietnam', 'iso3' => 'VNM', 'iso2' => 'VN', 'phone_code' => '84', 'currency' => 'VND', 'currency_name' => 'Vietnamese đồng', 'currency_symbol' => '₫'],
            ['name' => 'Virgin Islands (British)', 'iso3' => 'VGB', 'iso2' => 'VG', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Virgin Islands (US)', 'iso3' => 'VIR', 'iso2' => 'VI', 'phone_code' => '1', 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['name' => 'Wallis and Futuna Islands', 'iso3' => 'WLF', 'iso2' => 'WF', 'phone_code' => '681', 'currency' => 'XPF', 'currency_name' => 'CFP franc', 'currency_symbol' => '₣'],
            ['name' => 'Western Sahara', 'iso3' => 'ESH', 'iso2' => 'EH', 'phone_code' => '212', 'currency' => 'MAD', 'currency_name' => 'Moroccan dirham', 'currency_symbol' => 'MAD'],
            ['name' => 'Yemen', 'iso3' => 'YEM', 'iso2' => 'YE', 'phone_code' => '967', 'currency' => 'YER', 'currency_name' => 'Yemeni rial', 'currency_symbol' => '﷼'],
            ['name' => 'Zambia', 'iso3' => 'ZMB', 'iso2' => 'ZM', 'phone_code' => '260', 'currency' => 'ZMW', 'currency_name' => 'Zambian kwacha', 'currency_symbol' => 'ZK'],
            ['name' => 'Zimbabwe', 'iso3' => 'ZWE', 'iso2' => 'ZW', 'phone_code' => '263', 'currency' => 'ZWL', 'currency_name' => 'Zimbabwe Dollar', 'currency_symbol' => '$'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
